### PR TITLE
🔪 Remove unnused chalk dependency

### PR DESCRIPTION
**Pull request by jrolfs**

### CODE REVIEW

**Comment by nickcobbett** [comment]
no `yarn.lock` changes?

**Comment by jrolfs** [comment]
@dependabot recreate

**Comment by jrolfs** [comment]
@nickcobbett I think we still depend on **chalk** transitively (a dependency of a dependency) which would explain the lockfile not changing? I also noticed this when I made the change.

**Review by nickcobbett — APPROVED** [review]

**Pull request merged**
