### PR TITLE
✨ Expose ts-jest utils API

### PR DESCRIPTION
**Pull request by jrolfs**
- Use `lowercase` instead of `kebab-case` for **scope-case**
- Expose **ts-jest** `utils` at `@hover/javascript/api/test`

### CODE REVIEW

**Comment by jrolfs** [comment]
rebuild

**Comment by jrolfs** [comment]
rebuild

**Comment by jrolfs** [comment]
rebuild

**Comment by jrolfs** [comment]
rebuild

**Review by fiddlerwoaroof — APPROVED** [review]

**Pull request merged**
